### ISSUE TITLE
tSNE fails with FACS derived .fcs files

### ISSUE THREAD

**Issue by JamesBadger** [ManuSetty/wishbone#20]
Hi, 
I have no trouble using the notebook example .fcs or other mass cytometry .fcs files but when I attempt to use .fcs files derived from FACS data I can make scatter plots etc but tSNE fails. Are FACS derived .fcs files fully supported? Advice much appreciated. Error traceback below. 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-e7ad38ea1e56> in <module>()
----> 1 scdata.run_tsne()

/Users/James/anaconda/envs/sandbox/lib/python3.5/site-packages/wishbone-0.3-py3.5.egg/wishbone/wb.py in run_tsne(self, n_components)
    401 
    402         print('If running in notebook, please look at the command line window for tSNE progress log')
--> 403         self.tsne = pd.DataFrame(bh_sne(data),
    404                                  index=self.data.index, columns=['x', 'y'])
    405 

/Users/James/anaconda/envs/sandbox/lib/python3.5/site-packages/tsne-0.1.3-py3.5-macosx-10.6-x86_64.egg/tsne/__init__.py in bh_sne(data, pca_d, d, perplexity, theta)
     40 
     41     tsne = BH_SNE()
---> 42     Y = tsne.run(X, N, X.shape[1], d, perplexity, theta)
     43     return Y
     44 

tsne/bh_sne.pyx in bh_sne.BH_SNE.run (tsne/bh_sne.cpp:1496)()

ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'
```

**Comment by ManuSetty** [comment]
Hello

We havent tested Wishbone for FACS derived FCS file but this looks like an issue that can be fixed. Can you please email one of the fcs files you are using so that we can identify the cause of error and fix it? Email address is manu.setty @ columbia.edu [Remove the spaces]

Thanks

**Comment by ManuSetty** [comment]
This is now fixed in the develop branch. Please update your installation to the develop branch and let me know if there are further issues with the FACS data. 

```
git clone git://github.com/manusetty/wishbone.git
cd wishbone
git checkout develop
git pull origin develop
sudo pip3 install .

```

**Comment by JamesBadger** [comment]
Yes this work. Thanks for taking care of it.
