### ISSUE TITLE
pip installed .egg-info for wishbone, but do not see package/module

### ISSUE THREAD

**Issue by mike1wilk** [ManuSetty/wishbone#3]
Tried to import wishbone in python3, module was not found. Looked into the package folder and found only the .egg-info folder but no module/package was installed. Not sure if I am the only one getting this error since I had some trouble installing tsne, this is in `installed-files.txt`:
`PKG-INFO`
`SOURCES.txt`
`requires.txt`
`dependency_links.txt`
`top_level.txt`
`../../../../bin/wishbone_gui.py`

**Comment by ManuSetty** [comment]
Thanks for pointing this out. The wishbone package needed to be explicitly specified in the setup.py script. This has been fixed in #4 and released as v0.2.1
