### ISSUE TITLE
Re. Pseudotemporal ordering 

### ISSUE THREAD

**Issue by macsharma** [ManuSetty/wishbone#33]
Dear Sir,
How to obtain the pseudotemporal ordering from the wishbone python package.

Regards,

**Comment by ManuSetty** [comment]
Hello

I am not sure  I completely understand the question. If you are referring to extracting pseudo time after running Wishbone on the command line, the pseudotime/trajectory can be accessed using ```wb.trajectory```.

**Comment by macsharma** [comment]
Thanks
