### ISSUE TITLE
Re. Branching

### ISSUE THREAD

**Issue by macsharma** [ManuSetty/wishbone#34]
Dear sir,
Wishbone fails if there is no branching found

**Comment by macsharma** [comment]
also there is this error
KeyError                                  Traceback (most recent call last)
<ipython-input-18-9b190e22dc71> in <module>()
      7 scdata.run_diffusion_map_correlations()
      8 wb = wishbone.wb.Wishbone(scdata)
----> 9 wb.run_wishbone(start_cell='1C 1', components_list=[1, 2], num_waypoints=5)
     10 print(wb.trajectory.head())

/home/mayank/anaconda3/lib/python3.5/site-packages/wishbone-0.4.1-py3.5.egg/wishbone/wb.py in run_wishbone(self, start_cell, branch, k, components_list, num_waypoints)
   1062         res = wishbone.core.wishbone(
   1063             self.scdata.diffusion_eigenvectors.ix[:, components_list].values,
-> 1064             s=s, k=k, l=k, num_waypoints=num_waypoints, branch=branch)
   1065 
   1066         # Assign results

/home/mayank/anaconda3/lib/python3.5/site-packages/wishbone-0.4.1-py3.5.egg/wishbone/core.py in wishbone(data, s, k, l, num_graphs, num_waypoints, verbose, metric, voting_scheme, branch, flock_waypoints, band_sample, partial_order, search_connected_components)
     46 
     47                 #run traj. landmarks
---> 48                 traj, dist, iter_l, paths_l2l = _trajectory_landmarks( klnn, data, [s], num_waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
     49                 if branch:
     50                         if verbose:

/home/mayank/anaconda3/lib/python3.5/site-packages/wishbone-0.4.1-py3.5.egg/wishbone/core.py in _trajectory_landmarks(spdists, data, s, waypoints, partial_order, verbose, metric, flock_waypoints, band_sample, branch)
    259                 if i == 0:
    260                         dist = [list(temp[0].values())]
--> 261                         paths_l2l = [[paths[li] for li in l]]
    262                 else:
    263                         dist.append(list(temp[0].values()))

/home/mayank/anaconda3/lib/python3.5/site-packages/wishbone-0.4.1-py3.5.egg/wishbone/core.py in <listcomp>(.0)
    259                 if i == 0:
    260                         dist = [list(temp[0].values())]
--> 261                         paths_l2l = [[paths[li] for li in l]]
    262                 else:
    263                         dist.append(list(temp[0].values()))

KeyError: 275

**Comment by ManuSetty** [comment]
Hello

Please try increasing the 'k' parameter and the 'num_waypoints' parameter and let me know if you still run into these issues.

**Comment by macsharma** [comment]
Hi,
These issues still exist even on changing the params.

**Comment by ManuSetty** [comment]
What were the parameters you used ?

Can you also give me a brief over view of the type of data and system you are studying? Thanks

**Comment by macsharma** [comment]
I am using num_waypoints as 10,15 and K=5,10.
And I am using monocle's data.

**Comment by ManuSetty** [comment]
Can you please email the data matrix you are using to manu{.}talanki{a}gmail{.}com so that I can take a closer look ?

**Comment by macsharma** [comment]
Hi, 
Got it working finally with my data. Thanks a lot for the help.
