### ISSUE TITLE
scdata.run_diffusion_map_correlations()

### ISSUE THREAD

**Issue by agelber** [ManuSetty/wishbone#39]
Hi Manu,

I am getting this error:

`/usr/local/lib/python3.6/site-packages/wishbone/wb.py:712: RuntimeWarning: invalid value encountered in true_divide
  return ((vals * x).mean(axis=0) - mu_vals * mu_x) / (sigma_vals * sigma_x)`

when I try to run the diffusion correlations. Any idea why this might be happening?

Best,
Alon

**Comment by ManuSetty** [comment]
Hello - this should just be a warning and that shouldn't affect results. The correlation computation on some of the low expressed genes will lead to divide by zero warnings.
