### ISSUE TITLE
plot_marker_trajectory() error

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#41]
When I run the following command for single cell-
vals, fig, ax  = wb.plot_marker_trajectory(['KRT18', 'KRT19', 'KRT14', 'PCNA']);

It throws error -
ValueError: Wrong number of items passed 2, placement implies 1

Could you please suggest what that means? I have tried running on other single cell dataset, and it works fine.

**Comment by ManuSetty** [comment]
Can you send a traceback for the error ?

**Comment by Anushi** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-51-f3de56426849> in <module>()
----> 1 vals, fig, ax  = wb.plot_marker_trajectory(['KRT18', 'KRT19', 'KRT14', 'PCNA']);
      2 #vals, fig, ax  = wb.plot_marker_trajectory(['PGDFRA']);
      3 #vals, fig, ax  = wb.plot_marker_trajectory(['CD34']);
      4 #fig.savefig('/Users/anushi/unisyd_projects/sc_breast_cancer/data/graphs/wishbone_sca3456_vehicle_0.2/fig8.png')

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/wishbone/wb.py in plot_marker_trajectory(self, markers, show_variance, no_bins, smoothing_factor, min_delta, fig, ax)
   1159             trunk = self.branch[trajectory.index[0]]
   1160             branches = list( set( self.branch).difference([trunk]))
-> 1161             linetypes = pd.Series([':', '--'], index=branches)
   1162 
   1163 

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/pandas/core/series.py in __init__(self, data, index, dtype, name, copy, fastpath)
    248                                        raise_cast_failure=True)
    249 
--> 250                 data = SingleBlockManager(data, index, fastpath=True)
    251 
    252         generic.NDFrame.__init__(self, data, fastpath=True)

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/pandas/core/internals.py in __init__(self, block, axis, do_integrity_check, fastpath)
   4115         if not isinstance(block, Block):
   4116             block = make_block(block, placement=slice(0, len(axis)), ndim=1,
-> 4117                                fastpath=True)
   4118 
   4119         self.blocks = [block]

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/pandas/core/internals.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   2717                      placement=placement, dtype=dtype)
   2718 
-> 2719     return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
   2720 
   2721 # TODO: flexible with index=None and/or items=None

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/pandas/core/internals.py in __init__(self, values, ndim, fastpath, placement, **kwargs)
   1842 
   1843         super(ObjectBlock, self).__init__(values, ndim=ndim, fastpath=fastpath,
-> 1844                                           placement=placement, **kwargs)
   1845 
   1846     @property

/Applications/anaconda/envs/wishbone_python3/lib/python3.5/site-packages/pandas/core/internals.py in __init__(self, values, placement, ndim, fastpath)
    113             raise ValueError('Wrong number of items passed %d, placement '
    114                              'implies %d' % (len(self.values),
--> 115                                              len(self.mgr_locs)))
    116 
    117     @property

ValueError: Wrong number of items passed 2, placement implies 1

**Comment by ManuSetty** [comment]
Did you face any issues during the Wishbone run? Can you send the plot of the Wishbone trajectory and branch results projected on tSNE ?

**Comment by Anushi** [comment]
![fig7](https://user-images.githubusercontent.com/6533653/28232347-89afb9f0-6933-11e7-824e-75fa4a874179.png)

I have attached plot of Wishbone trajectory and branch results projected on tSNE.
I did not get any error while running wishbone itself.

**Comment by ManuSetty** [comment]
Hello

Looking at these plots, I am not sure Wishbone is completely appropriate for the task at hand. How confident are you that there are two branches in the data: please note that Wishbone assumes there is specifically two branches in the data.

**Comment by Anushi** [comment]
Thanks Manu for your reply. I will need to confirm with my team mates about the number of branches we expect. I will close this issue for now.

I have questions about wishbone for another dataset which seems to work fine, but will open that in another issue.
