### ISSUE TITLE
Branch point and starting cell plotting.

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#42]
Hi Manu,

I am using wishbone on our dataset which works fine and we are keen to use it further.  In the wishbone branch/trajectory plot, is it possible to identify or label branch point and starting cell?

Thanks for your support and apologies for troubling with too many questions.

**Comment by ManuSetty** [comment]
The index of the the start cell can be determined using ```wb.trajectory.idxmin()```


The branch point index can be determined using the following code snippet. This code is extracted from the ```plot_marker_trajectory``` function.

```
# Trajectory bins
no_bins = 150
trajectory = wb.trajectory.sort_values()
bins = np.linspace(np.min(trajectory), np.max(trajectory), no_bins)

# Branch counts
branch_counts = pd.DataFrame(np.zeros([len(bins)-1, 3]), columns=[1, 2, 3])
for j in branch_counts.columns:
    branch_counts[j] = pd.Series([sum(wb.branch[trajectory.index[(trajectory > bins[i-1]) & \
        (trajectory < bins[i])]] == j) for i in range(1, len(bins))])

# Frequencies
trunk = wb.branch[trajectory.index[0]]
branch_counts = branch_counts.divide( branch_counts.sum(axis=1), axis=0)
bp_bin = np.where(branch_counts[trunk] < 0.9)[0][0]

# Label
bp_index = np.idxmin(np.abs(trajectory - bins[bp_bin]))
```

**Comment by Anushi** [comment]
Thanks.
