### ISSUE TITLE
Diffusion components

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#43]
Hi Manu,

What do colors in each of the diffusion component mean? Also, is it possible to obtain/plot more than 10 diffusion components?

Thanks.

**Comment by ManuSetty** [comment]
The function by default determines the top 10 diffusion components. You can increase this by using the ```n_diffusion_components```` parameter in the ```run_diffusion_map``` function.

**Comment by Anushi** [comment]
Thanks.
