### ISSUE TITLE
module 'wishbone' has no attribute 'wb'

### ISSUE THREAD

**Issue by ToriiKotaro** [ManuSetty/wishbone#44]
Hi,

I have just started to use wishbone. 
However when I try to follow the tutorial I continually get the error: module 'wishbone' has no attribute 'wb'

Do you have any idea why this might be? 
I have anaconda installed with python 3.6.
Today I cloned packages from your GitHub repository, but  then I had to install only bhtsne manually.

Thanks,
Torii

**Comment by ManuSetty** [comment]
Please make sure you are not in the directory containing the downloaded wishbone module when you are trying to import wishbone

**Comment by ToriiKotaro** [comment]
When I am trying to import wishbone, I am in the directory containing the downloaded wishbone file.
Should I be in wishbone/src/wishbone when I import or create an object of the type wishbone.wb.SCData?

**Comment by ManuSetty** [comment]
You can be any directory other than the directory you downloaded wishbone to. If you are in the directory where wishbone was downloaded, python will try to import that copy rather than the installation resulting in the error you observe
