### ISSUE TITLE
plot_tsne_by_cell_sizes() question.

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#46]
Hi Manu,

In plot_tsne_by_cell_sizes() function, if I load data which is already normalised, what would cell size mean? In this case, tSNE would not have raw counts.

Thanks.

**Comment by ManuSetty** [comment]
I believe the function will result in an error if the data is already pre normalized.

**Comment by Anushi** [comment]
Actually I am using pre normalised dataset for plot_tsne_by_cell_sizes() and it does not throw any error.

**Comment by ManuSetty** [comment]
How are you loading the data? If you are using the ```from_csv``` function, the ```normalize``` parameter is set to ```True``` by default and normalizes the data by molecule size. There will be no issues if you performed a similar correction for your pre normalized data but if you not, you can consider turning of normalization
