### ISSUE TITLE
Pre normalised dataset

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#47]
Hi Manu,

For single cell, it it possible to use pre normalised dataset? I tried to run wishbone notebook on a pre-normalised dataset and it works fine. Does it mean it is normalising again?

Thanks.

**Comment by ManuSetty** [comment]
Please see response to issue #46

**Comment by Anushi** [comment]
Yes, I am using from_csv() function to load dataset which is pre-normalzed. Can turn-off normalisation option by normalize=False or normalize=None?

Thanks.

**Comment by ManuSetty** [comment]
Yes, it can be turned off by setting ```normalize=False```

**Comment by Anushi** [comment]
Thanks very much for your prompt responses.

**Comment by Anushi** [comment]
Hi Manu,

Does from_csv() require log transformed data? 

Thanks.

**Comment by ManuSetty** [comment]
No, that is not a requirement.

**Comment by Anushi** [comment]
I used normalize=False in from_csv() function. And scdata prints "normalized=True". Below is the output from scdata, any idea why would that be?

cluster_assignments=None
data_type=True
diffusion_eigenvalues=None
diffusion_eigenvectors=None
diffusion_map_correlations=None
library_sizes=True
metadata=True
normalized=True
pca=None
tsne=None

**Comment by ManuSetty** [comment]
The data is assumed to be normalized if normalize is set to False and hence the flag in the scdata object is set to True. Please let me know if this affects your downstream analyses in any manner
