### ISSUE TITLE
Color cells by phenotype information.

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#49]
Hi Manu,

Is there a way to color the cells in the branches/trunk by phenotype information? E.g if I want to overlay color cells by samples names. 

Thanks.

**Comment by ManuSetty** [comment]
I am not sure I understand. What kind of plot are you thinking about?

**Comment by Anushi** [comment]
![wishbone_plot](https://user-images.githubusercontent.com/6533653/28967662-98674454-795f-11e7-82c8-a3e2c6e9f097.jpg)

I have attached a picture of the plot I am thinking of. Something where the user can give prior information of each cell like sample name, cell type, state, treatment, etc.
So the plot can overlay such information.

Please let me know if it makes sense. And also please don't worry if it's too complicated or not really useful feature for wishbone.

**Comment by ManuSetty** [comment]
You can look at the ```Clustering of cells``` section for plots similar to this. The sample type can be used instead of clusters by setting ```scdata.cluster_assignments``` to the sample types. Then you can use ```plot_phenograph_clusters``` to make the plot required.
