### ISSUE TITLE
Waypoints as list

### ISSUE THREAD

**Issue by Anushi** [ManuSetty/wishbone#51]
Hi Manu,

I ran wishbone first time and extracted waypoints using [wb.waypoints]. I ran wishbone again by passing num_waypoints as list of waypoints identified in previous run.  But it throws error. Just wanted to know correct place or way of passing the list.

**Error -
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices**

Although my dataset is single cell data, I checked your example notebook from mass cytometry data. It shows an example by giving list of waypoints while running wishbone. It seems that waypoint names are expected in numeric, but my dataset has alphanumeric. 

Is there a way you could modify the function to accept alphanumeric names?  Or something I could try quickly myself?
 
Thanks,
Anushi

**Comment by Anushi** [comment]
Ok, so I figured it's expecting indices of the cells (waypoints) and not the names. 

Thanks.

**Comment by Anushi** [comment]
Hi Manu,

Would it be possible to give an example of using waypoint list on single cell example data? I tried to give waypoint list (by saving waypoints obtaine from previous run) and it throws error.  I have attached the csv file of waypoints.
[single_cell_waypoint_df.txt](https://github.com/ManuSetty/wishbone/files/1276085/single_cell_waypoint_df.txt)

Error thrown -

"IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"

Cheers,
Anushi

**Comment by ManuSetty** [comment]
You should be able to run it by referencing the waypoints variable

```
# First run
wb = wishbone.wb.Wishbone(scdata)
wb.run_wishbone(start_cell, components_list=[1, 2, 3], num_waypoints=100)

# Second run
wb2 = wishbone.wb.Wishbone(scdata)
wb2.run_wishbone(start_cell, components_list=[1, 2, 3], num_waypoints=wb.waypoints)
```

Just ensure that the parameter you pass is of type ```list```

**Comment by Anushi** [comment]
Thanks Manu.

Perhaps may be worthwhile also providing an option to set global random seed for wishbone library.
This will stabilise the wishbone results.
