### ISSUE TITLE
Error when running wb.run_wishbone

### ISSUE THREAD

**Issue by marcRDM** [ManuSetty/wishbone#53]
Hi there,

I can now run the notebook successfully until run_wishbone step. I have a 4727 cells x 32 genes object and I tried a bunch of different value for num_waypoints and k (as suggested in issue #29) and also a bunch of different start_cell. Is there any other parameter I can play with in that setting?

Thank you very much,

Cheers,
Marc

**Comment by ManuSetty** [comment]
Just to make sure I understand, are you running into the same error as issue #29 ? What values of num_waypoints and k have you explored

**Comment by marcRDM** [comment]
Yes exact same issue as #29!
100 < num_waypoints < 1000
25 < k < 250
more or less

**Comment by ManuSetty** [comment]
Do you have a cluster of cells which are very clear outliers making them disconnected to the graph ? It would be helpful to see the tSNE maps colored by the different diffusion components to diagnose the issue

**Comment by marcRDM** [comment]
Not really... Have a look
<img width="547" alt="colored_tsne" src="https://user-images.githubusercontent.com/26809677/32851985-83c59e22-ca2e-11e7-920d-82290072a213.png">

**Comment by ManuSetty** [comment]
This is a bit surprising. Which are the components you are using? Does the shortest path determination always fail at the same cell index?

**Comment by marcRDM** [comment]
I am using components 1 to 4. How do I know the cell index?

**Comment by ManuSetty** [comment]
```traceback()``` should show the index on which the method is failing.

**Comment by marcRDM** [comment]
Hi,
Sorry for my late answer.
I tried on a different .fcs file : 1644 cells x 32 genes and I got it to run with num_waypoints=1000, k=250. I guess I'll manage to get it to run on all my files by playing with those parameters enough...
How should I interpret the results depending on the k and num_waypoints values I have to set to get it to run..?

**Comment by ManuSetty** [comment]
I am a bit surprised as to why you need such a high k. Looking at the previous tSNE maps, it appears to me that your data is more a discrete set of clusters rather than a continuum. The discrete nature is most likely the reason for you needing to use high k.  If you have reason to believe this is indeed a continuous trajectory, the interpretation wouldn't necessarily change because you used a high value of k.

**Comment by marcRDM** [comment]
Alright, thank you very much!
One last thing : is there an implemented function that would draw the trajectory in a two-dimensional space? Coordinates on a pair of markers just like the first figure of your paper for instance?

**Comment by ManuSetty** [comment]
Which panel are you referring to? I can point you to the function or send you a snippet. But its certainly do-able

**Comment by marcRDM** [comment]
Something like left panel a!

**Comment by ManuSetty** [comment]
Ah, that was only for visualization and not generate automatically. You can color the scatter plots by trajectory. Look at the `wb.plot_wishbone_on_tsne ` function in the notebook [here](http://nbviewer.jupyter.org/github/ManuSetty/wishbone/blob/master/notebooks/Wishbone_for_mass_cytometry.ipynb#pre).

**Comment by ManuSetty** [comment]
Hello - I am closing this issue. Please report if you still have issues. Thanks!
