### ISSUE TITLE
Branching Function

### ISSUE THREAD

**Issue by Jaceves6** [ManuSetty/wishbone#58]
I was wondering how to run the program for data that does not branch. When running the Wishbone analysis, even when I uncheck the "Branch" box, the Wishbone visualization provided still has a branching point.

![capture](https://user-images.githubusercontent.com/34075765/36808298-8917c0c4-1c79-11e8-98e0-e6a693c112c0.PNG)
![capture](https://user-images.githubusercontent.com/34075765/36808337-a4df1d16-1c79-11e8-85de-7e5122e8bde9.PNG)

**Comment by pkathail** [comment]
Yes this seems to be a bug. I've just pushed a fix that should take care of it.

**Comment by Jaceves6** [comment]
Thank you. 
![capture](https://user-images.githubusercontent.com/34075765/36862865-f3107d22-1d3c-11e8-8cc3-b0b0653d9119.PNG)
