### ISSUE TITLE
How to analyze parameters not used in tSNE/trajectory analysis

### ISSUE THREAD

**Issue by Jaceves6** [ManuSetty/wishbone#60]
In the wishbone paper it says, "To further test Wishbone's accuracy, we evaluated the expression trends of markers not used while learning the trajectory." I have tried exporting FCS files with only the certain parameters wanted for analysis, but then I am unable to see the other parameter's (not included in the analysis) trajectories. However, if I upload the whole FCS file, then I can not find a way to run the tSNE or trajectory analysis on only certain parameters. Thank you.

**Comment by ManuSetty** [comment]
Hello

I suggest the following work around for this now. 

1. Run Wishbone with the markers you would like to use for learning the trajectory.
2. After running wishbone, replace the data frame in Wishbone with all the markers you would like to explore using
```wb.scdata.data = <dataframe containing all the markers>```

Note that the row names of the data frame i.e., cell identifiers should be same as before. Please let me know if this solves your problem

**Comment by Jaceves6** [comment]
How do you only run Wishbone on specific trajectories?

**Comment by ManuSetty** [comment]
You can load the fcs file and subset the data frame for the markers of your choice

**Comment by Jaceves6** [comment]
Is it possible to run Wishbone on specific markers using the Wishbone_gui

**Comment by ManuSetty** [comment]
Unfortunately, we do not support selecting markers using the GUI. The best way to do it would be to export an fcs file with the markers you are interested in and running Wishbone. But if you are interested in running Wishbone on one set of markers and visualizing their behavior on a set of markets not included when running Wishbone, it is better to follow the structure in the jupyter notebook and the suggestion above.

**Comment by Jaceves6** [comment]
Thank you.
