### ISSUE TITLE
Problem running GSEA

### ISSUE THREAD

**Issue by ibrahimelhamamy** [ManuSetty/wishbone#61]
Hi, 

I have problems running gsea on wishbone. It just outputs a lot of error files and I am not sure why. I have all dependencies installed incl. Cython and numpy

scdata.run_gsea(output_stem= os.path.expanduser('/Users/ielhamamy/wishbone/tools/mouse'),gmt_file=('mouse', 'gofat.cc.v1.0.gmt.txt'))

1214 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_1.rnk
2674 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
2674 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
2768 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
2885 [INFO ] Done preproc for smaller than: 50
2898 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_1.GseaPreranked.1522107221521
4078 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_2.rnk
5427 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
5428 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
5512 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
5645 [INFO ] Done preproc for smaller than: 50
5654 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_2.GseaPreranked.1522107224407
6787 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_3.rnk
8094 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
8095 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
8180 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
8313 [INFO ] Done preproc for smaller than: 50
8326 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_3.GseaPreranked.1522107227042
9490 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_4.rnk
0866 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
0866 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
0949 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
1080 [INFO ] Done preproc for smaller than: 50
1091 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_4.GseaPreranked.1522107229787
2239 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_5.rnk
3614 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
3614 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
3706 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
3837 [INFO ] Done preproc for smaller than: 50
3848 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_5.GseaPreranked.1522107232529
5020 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_6.rnk
6486 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
6486 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
6577 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
6712 [INFO ] Done preproc for smaller than: 50
6724 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_6.GseaPreranked.1522107235329
7871 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_7.rnk
9322 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
9322 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
9409 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
9538 [INFO ] Done preproc for smaller than: 50
9549 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_7.GseaPreranked.1522107238152
0732 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_8.rnk
2114 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
2115 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
2202 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
2325 [INFO ] Done preproc for smaller than: 50
2337 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_8.GseaPreranked.1522107241021
3518 [INFO ] Begun importing: RankedList from: /Users/ielhamamy/wishbone/tools/mouse_cmpnt_9.rnk
4880 [INFO ] No ranked list collapsing was done .. using original as is
to parse>/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt< got: [/Users/ielhamamy/.wishbone/tools/mouse/gofat.cc.v1.0.gmt.txt]
4881 [INFO ] Begun importing: GeneSetMatrix from: gofat.cc.v1.0.gmt.txt
4962 [INFO ] Got gsets: 414 now preprocessing them ... min: 50 max: 500
5102 [INFO ] Done preproc for smaller than: 50
5113 [INFO ] Renaming rpt dir on error to: /Users/ielhamamy/wishbone/tools/error_mouse_9.GseaPreranked.1522107243784

Thanks in advance!
Ibrahim

**Comment by ManuSetty** [comment]
Hello

A couple of reasons why this error might be showing up

1. Are the gene names in your matrix official symbols?
2. The gene names also need to be in all upper case because of the way the gmt file is defined.

**Comment by ibrahimelhamamy** [comment]
Converted the gene names to uppercase letters, and it's now working! Thanks!
