### ISSUE TITLE
Problem with GSEA

### ISSUE THREAD

**Issue by rng-caltech** [ManuSetty/wishbone#62]
When I don't specify the gmt_file, the function works fine. 
`scdata.run_gsea( output_stem= os.path.expanduser('~/.wishbone/gsea/mouse_marrow'))`

```
Available GSEA .gmt files:

mouse:
gofat.bp.v1.0.gmt.txt
gofat.cc.v1.0.gmt.txt
gofat.mf.v1.0.gmt.txt

human:
c1.all.v5.0.symbols.gmt.txt
c2.all.v5.0.symbols.gmt.txt
c3.all.v5.0.symbols.gmt.txt
c5.all.v5.0.symbols.gmt.txt
c6.all.v5.0.symbols.gmt.txt
c7.all.v5.0.symbols.gmt.txt
gofat.bp.v1.0.gmt.txt
gofat.cc.v1.0.gmt.txt
gofat.mf.v1.0.gmt.txt
h.all.v5.0.symbols.gmt.txt

Please specify the gmt_file parameter as gmt_file=(organism, filename)
```
However, if I specify the gmt_file, I get this same error when running GSEA in the tutorial notebook or GUI. 

I ran the following code in the provided jupyter notebook and got the following error
`reports = scdata.run_gsea(output_stem= os.path.expanduser('~/.wishbone/gsea/mouse_marrow'), 
                    gmt_file=('mouse', 'gofat.bp.v1.0.gmt.txt'))`

```
If running in notebook, please look at the command line window for GSEA progress log
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-19-c95b7729cf31> in <module>()
      1 reports = scdata.run_gsea(output_stem= os.path.expanduser('~/.wishbone/gsea/mouse_marrow'), 
----> 2                     gmt_file=('mouse', 'gofat.bp.v1.0.gmt.txt'))

~\Anaconda3\lib\site-packages\wishbone\wb.py in run_gsea(self, output_stem, gmt_file, components, enrichment_threshold)
    879         for c in components:
    880             res = self._gsea_process( c, self._diffusion_map_correlations,
--> 881                 output_stem, gmt_file )
    882             # Load results
    883             if res == b'':

~\Anaconda3\lib\site-packages\wishbone\wb.py in _gsea_process(c, diffusion_map_correlations, output_stem, gmt_file)
    823 
    824         # Call GSEA
--> 825         p = Popen(cmd, stderr=PIPE)
    826         _, err = p.communicate()
    827 

~\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    707                                 c2pread, c2pwrite,
    708                                 errread, errwrite,
--> 709                                 restore_signals, start_new_session)
    710         except:
    711             # Cleanup if the child failed starting.

~\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified
```

When I try GSEA in the gui, the following error appears in the command prompt:

```Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\rache\Anaconda3\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "wishbone_gui.py", line 300, in runGSEA
    gmt_file=(gmt_file_type, self.GSEAFileName.split('/')[-1]))
  File "C:\Users\rache\Anaconda3\lib\site-packages\wishbone\wb.py", line 881, in run_gsea
    output_stem, gmt_file )
  File "C:\Users\rache\Anaconda3\lib\site-packages\wishbone\wb.py", line 825, in _gsea_process
    p = Popen(cmd, stderr=PIPE)
  File "C:\Users\rache\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\rache\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ManuSetty** [comment]
I believe this is an issue because of the way paths are constructed in the ```run_gsea``` function. The  path construction assumes a UNIX based system.

A minor update to the script should be able to fix this:
1.  Update line 871 in wb.py to ```gmt_file = os.path.expanduser('~\.wishbone\tools\{}\{}').format(*gmt_file)```
2. Reinstall Wishbone

Let me know if this resolves your issues.

**Comment by rng-caltech** [comment]
Thanks for the quick reply. I have updated wb.py and reinstalled wishbone, but it has not resolved the issue.

**Comment by ManuSetty** [comment]
The ```output_stem``` parameter in your function call should also be updated to have backslashes instead of forward slashes

Use ```output_stem= os.path.expanduser('~\.wishbone\gsea\mouse_marrow')```. I would also suggest to put the results in a different folder

**Comment by rng-caltech** [comment]
I tested backwards and forward slashes in command prompt and they both worked; however, I found out that `~` is not supported. run_gsea works now after I replaced `~` with my full directory in the cmd call, gmt_file, and output_stem. (Please excuse my poor choice of location for cloning wishbone)

Update location of output files in function calls:
`reports = scdata.run_gsea(output_stem= 'c:/Users/rache/Documents/Wishbone/gsea/mouse_marrow', 
                    gmt_file=('mouse', 'gofat.bp.v1.0.gmt.txt'))`

Update location of gmt file in run_gsea in wb.py:
`gmt_file = os.path.expanduser('c:/Users/rache/Documents/Wishbone/tools/{}/{}').format(*gmt_file)`

Update location of jar file in _gsea_process in wb.py:
`cmd = shlex.split(
            'java -cp {user}/Documents/Wishbone/tools/gsea2-2.2.1.jar -Xmx1g '
            'xtools.gsea.GseaPreranked -collapse false -mode Max_probe -norm meandiv '
            '-nperm 1000 -include_only_symbols true -make_sets true -plot_top_x 0 '
            '-set_max 500 -set_min 50 -zip_report false -gui false -rnk {rnk} '
            '-rpt_label {out_prefix}_{component} -out {out_dir}/ -gmx {gmt_file}'
            ''.format(user=os.path.expanduser('C:/Users/rache'), rnk=genes_file,
                      out_prefix=out_prefix, component=c, out_dir=out_dir,
                      gmt_file=gmt_file))`
