### ISSUE TITLE
wishbone_gui.py

### ISSUE THREAD

**Issue by CyTOF** [ManuSetty/wishbone#65]
Traceback (most recent call last):
  File "/usr/local/bin/wishbone_gui.py", line 5, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg'

**Comment by ManuSetty** [comment]
Can you provide us a few more details of the platform you are using? In general, the GUI has not been constantly maintained and we recommend using the python notebooks instead of the GUI.

**Comment by yang-dongxu** [comment]
I have meet the same question here, and after I try to fix this by https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/2 and https://www.developpez.net/forums/d1952557/autres-langages/python-zope/general-python/pb-navigationtoolbar2tkagg/
,I get a different error :

Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(wishbone_gui.py:586): Gdk-CRITICAL **: 17:25:09.541: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(wishbone_gui.py:586): Gdk-CRITICAL **: 17:25:09.547: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "/usr/local/bin/wishbone_gui.py", line 14, in <module>
    import wishbone
  File "/usr/local/lib/python3.6/dist-packages/wishbone/__init__.py", line 1, in <module>
    from . import wishbone_gui
  File "/usr/local/lib/python3.6/dist-packages/wishbone/wishbone_gui.py", line 4, in <module>
    matplotlib.use("TkAgg")
  File "/home/ydx/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1391, in use
    switch_backend(name)
  File "/home/ydx/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 222, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running.


I'm running on wsl -ubuntu16.04 with python3.6.7, and the xming is configured.

**Comment by ManuSetty** [comment]
You can try editing the line ```matplotlib.use("TkAgg")``` in ```matplotlib_gui.py``` to ```matplotlib.use("Agg")```, reinstall the package and try again.

**Comment by yang-dongxu** [comment]
That works, thank you
I make changes below:
  2
  3 import matplotlib
  4 #matplotlib.use("TkAgg")
  5
  6 matplotlib.use("Agg")
  7 #from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
  8 from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
  9 from matplotlib.backends.backend_tkagg import  NavigationToolbar2Tk as   NavigationToolbar2TkAgg
 10

**Comment by ManuSetty** [comment]
Great! Closing the issue.
